[package]
name    = "embedded-timeout-macros"
version = "0.1.0"
authors = ["Hanno Braun <hanno@braun-robotics.com>"]
edition = "2018"

[dependencies]
embedded-hal = "0.2.2"
nb           = "0.1.1"

[dev-dependencies]
void = "1.0.2"
